title: API Stack Network - Royal Bank of Scotland
url: royal-bank-of-scotland.stack.network
tag: Royal Bank of Scotland
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: api-stack-providers
github_repo: royal-bank-of-scotland
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
